/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.bruno.gestaofinanceira.util;

/**
 *
 * @author bruno
 */
public class RemovePopUp extends javax.swing.JFrame {

    /**
     * Creates new form RemovePopUp
     */
    public RemovePopUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPopup = new javax.swing.JPanel();
        panelPopup2 = new javax.swing.JPanel();
        labelPopup2 = new javax.swing.JLabel();
        LabelPopup3 = new javax.swing.JLabel();
        LabelPopup4 = new javax.swing.JLabel();
        LabelNo = new javax.swing.JLabel();
        LabelYes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPopup.setBackground(new java.awt.Color(49, 56, 65));
        panelPopup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPopup2.setBackground(new java.awt.Color(28, 36, 47));
        panelPopup2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPopup2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        labelPopup2.setForeground(new java.awt.Color(255, 255, 255));
        labelPopup2.setText(" Tem certeza que deseja");
        panelPopup2.add(labelPopup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 270, 37));

        LabelPopup3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        LabelPopup3.setForeground(new java.awt.Color(255, 255, 255));
        LabelPopup3.setText("deletar essa compra?");
        panelPopup2.add(LabelPopup3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 240, 39));

        panelPopup.add(panelPopup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 290, -1));

        LabelPopup4.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        LabelPopup4.setForeground(new java.awt.Color(248, 69, 69));
        LabelPopup4.setText("*Todos os dados dessa compra serão excluidos!*");
        panelPopup.add(LabelPopup4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 330, 40));

        LabelNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nao.png"))); // NOI18N
        LabelNo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelNoMouseClicked(evt);
            }
        });
        panelPopup.add(LabelNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 290, 40));

        LabelYes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sim.png"))); // NOI18N
        LabelYes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelYesMouseClicked(evt);
            }
        });
        panelPopup.add(LabelYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 290, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPopup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPopup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelNoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelNoMouseClicked

    private void LabelYesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelYesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelYesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemovePopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemovePopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemovePopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemovePopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemovePopUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNo;
    private javax.swing.JLabel LabelPopup3;
    private javax.swing.JLabel LabelPopup4;
    private javax.swing.JLabel LabelYes;
    private javax.swing.JLabel labelPopup2;
    private javax.swing.JPanel panelPopup;
    private javax.swing.JPanel panelPopup2;
    // End of variables declaration//GEN-END:variables
}
